ALTER TABLE IF EXISTS "users" DROP CONSTRAINT IF EXISTS "users_group_key_fkey";

ALTER TABLE IF EXISTS "items" DROP CONSTRAINT IF EXISTS "items_group_key_fkey";

DROP TABLE IF EXISTS "items";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "groups";