// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Group struct {
	GroupKey string `json:"group_key"`
}

type Item struct {
	ID          int64  `json:"id"`
	UserEmail   string `json:"user_email"`
	Description string `json:"description"`
	GroupKey    string `json:"group_key"`
	Checked     bool   `json:"checked"`
}

type User struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
	GroupKey       string `json:"group_key"`
}
